artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  preprocessed_train_data_path: artifacts/data_preprocessing/preprocessed_train.joblib
  preprocessed_test_data_path: artifacts/data_preprocessing/preprocessed_test.joblib
  tokenizer_path: artifacts/data_preprocessing/vectorizer.joblib

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_preprocessing/preprocessed_train.joblib
  test_data_path: artifacts/data_preprocessing/preprocessed_test.joblib
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_preprocessing/preprocessed_blind_test.joblib
  model_path: artifacts/model_training/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

bilstm_training:
  root_dir: artifacts/bilstm_training
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  tokenizer_path: artifacts/bilstm_training/keras_tokenizer.joblib
  fasttext_model_path: artifacts/bilstm_training/fasttext_model.bin
  model_path: artifacts/bilstm_training/bilstm_model.keras
  optimal_thresholds_path: artifacts/bilstm_training/optimal_thresholds.joblib

bilstm_evaluation:
  root_dir: artifacts/bilstm_evaluation
  test_data_path: artifacts/data_ingestion/test.csv
  keras_tokenizer_path: artifacts/bilstm_training/keras_tokenizer.joblib
  model_path: artifacts/bilstm_training/bilstm_model.keras
  optimal_thresholds_path: artifacts/bilstm_training/optimal_thresholds.joblib
  metric_file_name: artifacts/bilstm_evaluation/metrics.json
